### ISSUE TITLE
Error: Run WordPress Container Setup Script

### ISSUE THREAD

**Issue by iamrauu** [elegantthemes/create-divi-extension#242]
### Problem Description
Error downloading Wordpress during initial setup on step **Run WordPress Container Setup Script**
https://www.elegantthemes.com/documentation/developers/divi-development-environment/

### Steps To Reproduce
1.Execute `docker-compose exec -u 1000 wordpress divi-dev setup` 

### Screenshot and/or gif
![image](https://user-images.githubusercontent.com/139956/55256685-0e1bf100-5234-11e9-8d82-bd3eb623d7c3.png)

**Comment by lots0logs** [comment]
Looks like you have an outdated image. Run `docker pull elegantthemes/divi-dev` and then try again.

**Comment by mortan66** [comment]
I'm having the same issue with the latest image. macOS 10.12.6 with docker version 18.09.2

**Comment by iamrauu** [comment]
> Looks like you have an outdated image. Run `docker pull elegantthemes/divi-dev` and then try again.

Thanks @lots0logs - that didn't work for me.

**Comment by mangomkt** [comment]
I have the same issue.... cannot download wordpress

**Comment by lots0logs** [comment]
Could you provide the output of `docker images`?

**Comment by douglasgough** [comment]
Happy to find I'm not alone. I have the same issue, but I'm on Ubuntu 18.10.

docker images output:

REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
elegantthemes/divi-dev   latest              0366353c4689        4 weeks ago         456MB
hello-world              latest              fce289e99eb9        3 months ago        1.84kB
mariadb                  10.2.14             2cbeee8bd9cf        10 months ago       399MB

**Comment by lots0logs** [comment]
You have an outdated copy of the image. Did you run `docker pull elegantthemes/divi-dev`?

**Comment by douglasgough** [comment]
I just did the image update and am trying again.

Sorry, but I still have the problem.

**Comment by douglasgough** [comment]
After running docker pull elegantthemes/divi-dev and then docker images:

`elegantthemes/divi-dev   latest              0366353c4689        4 weeks ago         456MB
`

**Comment by lots0logs** [comment]
Okay looks like the tag didn't update properly on docker hub. I fixed it. Run docker pull again and then it should work.

**Comment by douglasgough** [comment]
It pulled the latest version, but I still get the error. `docker images` shows this:

`elegantthemes/divi-dev   latest              216d801fb9a1        5 days ago          500MB
elegantthemes/divi-dev   <none>              0366353c4689        4 weeks ago         456MB
`
Do I need to get rid of the old image somehow?

**Comment by lots0logs** [comment]
Make sure you start with a fresh directory. Remove any directories inside it that were created by the container in your previous attempts.

**Comment by douglasgough** [comment]
I'll try that

**Comment by douglasgough** [comment]
I might need your help with the directories. I'm new to docker. I've always used Vagrant. I currently have one directory under /home/douglas/wpdevel in which I have my docker-compose.yml. There are no dirs under that, so I don't know what to remove.

**Comment by lots0logs** [comment]
As long as the only thing in the directory is the compose file then you are good. What is the output when you try to start the container using the compose command in our docs?

**Comment by douglasgough** [comment]
I decided to nuke all my containers and images and start over. 
Then I ran `docker-compose exec -u 1000 wordpress divi-dev setup`
And it works!

**Comment by douglasgough** [comment]
I used the instructions here to learn how to clear out unused/unwanted images and containers:
https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes
